name: flutter_fianl_prj
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  logger: ^0.9.4
  timer_builder: ^2.0.0
  date_format: ^2.0.2
  google_maps_flutter: ^1.0.5
  flutter_form_builder: ^3.14.1
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/splash.png
    - images/mainhyimg.png
    - images/loginhyimg.png
    - images/symbol.png
    - images/101desc1st.png
    - images/101desc2nd.png
    - images/101desc3rd.png
    - images/101desc4th.png
    - images/101desc5th.png
    - images/101img1st.png
    - images/101img2nd.png
    - images/101img3rd.png
    - images/101img4th.png
    - images/101img5th.png
    - images/102desc1st.png
    - images/102desc2nd.png
    - images/102desc3rd.png
    - images/102desc4th.png
    - images/102desc5th.png
    - images/102img1st.png
    - images/102img2nd.png
    - images/102img3rd.png
    - images/102img4th.png
    - images/102img5th.png
    - images/103descb1st.png
    - images/103desc1st.png
    - images/103desc2nd.png
    - images/103desc3rd.png
    - images/103desc4th.png
    - images/103desc5th.png
    - images/103imgb1st.png
    - images/103img1st.png
    - images/103img2nd.png
    - images/103img3rd.png
    - images/103img4th.png
    - images/103img5th.png
    - images/104descb1st.png
    - images/104desc1st.png
    - images/104desc2nd.png
    - images/104desc3rd.png
    - images/104desc4th.png
    - images/104desc5th.png
    - images/104imgb1st.png
    - images/104img1st.png
    - images/104img2nd.png
    - images/104img3rd.png
    - images/104img4th.png
    - images/104img5th.png
    - images/105descb1st.png
    - images/105desc1st.png
    - images/105desc2nd.png
    - images/105desc3rd.png
    - images/105desc4th.png
    - images/105desc5th.png
    - images/105imgb1st.png
    - images/105img1st.png
    - images/105img2nd.png
    - images/105img3rd.png
    - images/105img4th.png
    - images/105img5th.png
    - images/201desc1st.png
    - images/201desc2nd.png
    - images/201desc3rd.png
    - images/201desc4th.png
    - images/201desc5th.png
    - images/201img1st.png
    - images/201img2nd.png
    - images/201img3rd.png
    - images/201img4th.png
    - images/201img5th.png
    - images/202desc1st.png
    - images/202desc2nd.png
    - images/202desc3rd.png
    - images/202desc4th.png
    - images/202desc5th.png
    - images/202img1st.png
    - images/202img2nd.png
    - images/202img3rd.png
    - images/202img4th.png
    - images/202img5th.png
    - images/110desc1st.png
    - images/110desc2nd.png
    - images/110desc3rd.png
    - images/110desc4th.png
    - images/110img1st.png
    - images/110img2nd.png
    - images/110img3rd.png
    - images/110img4th.png
    - images/109desc1st.png
    - images/109img1st.png
    - images/111desc1st.png
    - images/111desc2nd.png
    - images/111desc3rd.png
    - images/111img1st.png
    - images/111img2nd.png
    - images/111img3rd.png
    - images/403desc1st.png
    - images/403desc2nd.png
    - images/403desc3rd.png
    - images/403img1st.png
    - images/403img2nd.png
    - images/403img3rd.png
    - images/309descb1st.png
    - images/309desc1st.png
    - images/309desc2nd.png
    - images/309desc3rd.png
    - images/309desc4th.png
    - images/309imgb1st.png
    - images/309img1st.png
    - images/309img2nd.png
    - images/309img3rd.png
    - images/309img4th.png
    - images/204descb1st.png
    - images/204desc1st.png
    - images/204desc2nd.png
    - images/204desc3rd.png
    - images/204desc4th.png
    - images/204imgb1st.png
    - images/204img1st.png
    - images/204img2nd.png
    - images/204img3rd.png
    - images/204img4th.png
    - images/205descb1st.png
    - images/205desc1st.png
    - images/205desc2nd.png
    - images/205desc3rd.png
    - images/205desc4th.png
    - images/205imgb1st.png
    - images/205img1st.png
    - images/205img2nd.png
    - images/205img3rd.png
    - images/205img4th.png
    - images/207desc1st.png
    - images/207desc2nd.png
    - images/207desc3rd.png
    - images/207desc4th.png
    - images/207desc5th.png
    - images/207desc6th.png
    - images/207img1st.png
    - images/207img2nd.png
    - images/207img3rd.png
    - images/207img4th.png
    - images/207img5th.png
    - images/207img6th.png
    - images/402desc1st.png
    - images/402desc2nd.png
    - images/402desc3rd.png
    - images/402img1st.png
    - images/402img2nd.png
    - images/402img3rd.png
    - images/311descb1st.png
    - images/311desc1st.png
    - images/311desc2nd.png
    - images/311desc3rd.png
    - images/311desc4th.png
    - images/311desc5th.png
    - images/311desc6th.png
    - images/311imgb1st.png
    - images/311img1st.png
    - images/311img2nd.png
    - images/311img3rd.png
    - images/311img4th.png
    - images/311img5th.png
    - images/311img6th.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Gothic
       fonts:
         - asset: fonts/GothicA1Bold.ttf
         - asset: fonts/GothicA1Medium.ttf
     - family: GodoM
       fonts:
         - asset: fonts/GodoM.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
